on: 
  push:
    paths-ignore:
      - './github/**'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: pwd
      - uses: actions/checkout@v3
      - run: pwd
      - run: touch nacho.txt
      - run: echo "Hola " >> nacho2.txt
      - id: foo
        uses: nachoborente/hello-world-composite-action@v4
        with:
          who-to-greet: 'Nacho DevOps'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

